# Generated by Django 5.1.4 on 2025-01-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
